CREATE TABLE IF NOT EXISTS users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fio varchar(255) NOT NULL,
    phone varchar(12) NOT NULL,
    login varchar(50) NOT NULL,
    password varchar(30) NOT NULL,
    type varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    start_date date NOT NULL,
    org_tech_type text NOT NULL,
    org_tech_model text NOT NULL,
    problem_description text NOT NULL,
    request_status varchar(64) NOT NULL,
    completion_date date,
    repair_parts text,
    masterID integer REFERENCES users(id),
    clientID integer REFERENCES users(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message text NOT NULL,
    masterID integer REFERENCES users(id),
    requestID integer REFERENCES requests(id) NOT NULL
);